name: firstWorkflow
on: Workflow_dispatch
jobs:
  firstjob:
    runs-on: windows-latest
    steps:
      - name: print greeting
        run: echo "Hello world!"
      - name: print goodbye
        run: echo "Done - Good bye!"
